// Mapping from local authorities to UK regions
export const LOCAL_AUTHORITY_TO_REGION: Record<string, string> = {
  // East Midlands
  Derby: "England - East Midlands",
  Derbyshire: "England - East Midlands",
  Leicester: "England - East Midlands",
  Leicestershire: "England - East Midlands",
  Lincolnshire: "England - East Midlands",
  Northamptonshire: "England - East Midlands",
  Nottingham: "England - East Midlands",
  Nottinghamshire: "England - East Midlands",
  Rutland: "England - East Midlands",
  // East of England
  Bedfordshire: "England - East of England",
  "Central Bedfordshire": "England - East of England",
  Bedford: "England - East of England",
  Luton: "England - East of England",
  Cambridgeshire: "England - East of England",
  Peterborough: "England - East of England",
  Essex: "England - East of England",
  "Southend-on-Sea": "England - East of England",
  Thurrock: "England - East of England",
  Hertfordshire: "England - East of England",
  Norfolk: "England - East of England",
  Suffolk: "England - East of England",
  // London
  "Greater London": "England - London",
  "City of London": "England - London",
  // North East
  "County Durham": "England - North East",
  Darlington: "England - North East",
  Hartlepool: "England - North East",
  Middlesbrough: "England - North East",
  Northumberland: "England - North East",
  "Redcar and Cleveland": "England - North East",
  "Stockton-on-Tees": "England - North East",
  "Tyne and Wear": "England - North East",
  "Newcastle upon Tyne": "England - North East",
  Gateshead: "England - North East",
  "South Tyneside": "England - North East",
  "North Tyneside": "England - North East",
  Sunderland: "England - North East",
  // North West
  Cheshire: "England - North West",
  "Cheshire East": "England - North West",
  "Cheshire West and Chester": "England - North West",
  Cumbria: "England - North West",
  "Greater Manchester": "England - North West",
  Lancashire: "England - North West",
  Merseyside: "England - North West",
  Liverpool: "England - North West",
  Warrington: "England - North West",
  "Blackburn with Darwen": "England - North West",
  Blackpool: "England - North West",
  // South East
  Berkshire: "England - South East",
  Buckinghamshire: "England - South East",
  "East Sussex": "England - South East",
  Hampshire: "England - South East",
  "Isle of Wight": "England - South East",
  Kent: "England - South East",
  Oxfordshire: "England - South East",
  Surrey: "England - South East",
  "West Sussex": "England - South East",
  "Brighton and Hove": "England - South East",
  Portsmouth: "England - South East",
  Southampton: "England - South East",
  "Milton Keynes": "England - South East",
  Medway: "England - South East",
  Slough: "England - South East",
  Reading: "England - South East",
  "West Berkshire": "England - South East",
  Wokingham: "England - South East",
  "Windsor and Maidenhead": "England - South East",
  "Bracknell Forest": "England - South East",
  // South West
  Bristol: "England - South West",
  Cornwall: "England - South West",
  Devon: "England - South West",
  Dorset: "England - South West",
  Gloucestershire: "England - South West",
  Somerset: "England - South West",
  Wiltshire: "England - South West",
  "Bath and North East Somerset": "England - South West",
  "North Somerset": "England - South West",
  "South Gloucestershire": "England - South West",
  Bournemouth: "England - South West",
  Poole: "England - South West",
  Plymouth: "England - South West",
  Torbay: "England - South West",
  Swindon: "England - South West",
  // West Midlands
  Herefordshire: "England - West Midlands",
  Shropshire: "England - West Midlands",
  Staffordshire: "England - West Midlands",
  "Stoke-on-Trent": "England - West Midlands",
  Warwickshire: "England - West Midlands",
  "West Midlands": "England - West Midlands",
  Birmingham: "England - West Midlands",
  Worcestershire: "England - West Midlands",
  "Telford and Wrekin": "England - West Midlands",
  // Yorkshire and The Humber
  "East Riding of Yorkshire": "England - Yorkshire and The Humber",
  "Kingston upon Hull": "England - Yorkshire and The Humber",
  "North East Lincolnshire": "England - Yorkshire and The Humber",
  "North Lincolnshire": "England - Yorkshire and The Humber",
  "North Yorkshire": "England - Yorkshire and The Humber",
  "South Yorkshire": "England - Yorkshire and The Humber",
  "West Yorkshire": "England - Yorkshire and The Humber",
  York: "England - Yorkshire and The Humber",
} as const;
